--LOAD INTO NEW TABLE
SELECT * 
INTO ref.blocks
FROM [ws].[dbo].[BLK2010]

--CREATE A PRIMARY KEY SO WE CAN CREATE A SPATIAL INDEX
ALTER TABLE ref.blocks ALTER COLUMN BLOCKID10 nvarchar(15) NOT NULL
ALTER TABLE ref.blocks ADD CONSTRAINT pk_ref_blocks_blockid10 PRIMARY KEY CLUSTERED (BLOCKID10) 

--SET THE SHAPES TO BE NOT NULL SO WE CAN CREATE A SPATIAL INDEX
ALTER TABLE ref.blocks ALTER COLUMN shape geometry NOT NULL

--SELECT max(x_coord), min(x_coord), max(y_coord), min(y_coord) from gis.parcels
CREATE SPATIAL INDEX [ix_spatial_ref_blocks] ON ref.blocks
(
    shape
) USING  GEOMETRY_GRID
    WITH (BOUNDING_BOX =(6152300, 1775400, 6613100, 2129400), GRIDS =(LEVEL_1 = MEDIUM,LEVEL_2 = MEDIUM,LEVEL_3 = MEDIUM,LEVEL_4 = MEDIUM), 
    CELLS_PER_OBJECT = 16, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
