USE spacecore
IF OBJECT_ID('input.costar', 'u') IS NOT NULL
	DROP TABLE input.costar
GO
CREATE TABLE input.costar(
	[property_id] bigint NOT NULL		--change [PropertyID] to [property_id]
	,[amenities] nvarchar(max) NULL
	,[anchor_tenants] nvarchar(max) NULL
	,[architect_name] nvarchar(max) NULL
	,[average_weighted_rent] numeric(38,8) NULL
	,[avg_rent_direct_(industrial)] numeric(38,8) NULL
	,[avg_rent_direct_(office)] numeric(38,8) NULL
	,[avg_rent_direct_(retail)] numeric(38,8) NULL
	,[avg_rent_sublet_(industrial)] numeric(38,8) NULL
	,[avg_rent_sublet_(office)] numeric(38,8) NULL
	,[avg_rent_sublet_(retail)] numeric(38,8) NULL
	,[building_address] nvarchar(max) NULL
	,[building_class] nvarchar(1) NULL
	,[building_location] nvarchar(max) NULL
	,[building_name] nvarchar(max) NULL
	,[building_operating_expenses] nvarchar(max) NULL
	,[building_park] nvarchar(max) NULL
	,[building_status] nvarchar(max) NULL
	,[building_tax_expenses] nvarchar(max) NULL
	,[ceiling_height_range] nvarchar(max) NULL
	,[city] nvarchar(max) NULL
	,[closest_transit_stop] nvarchar(max) NULL
	,[closest_transit_stop_dist_(mi)] numeric(38,8) NULL
	,[closest_transit_stop_walk_time_(min)] tinyint NULL
	,[column_spacing] nvarchar(max) NULL
	,[construction_material] nvarchar(max) NULL
	,[core_factor] numeric(38,8) NULL
	,[county_name] nvarchar(max) NULL
	,[cross_street] nvarchar(max) NULL
	,[developer_name] nvarchar(max) NULL
	,[direct_available_space] int NULL
	,[direct_services] nvarchar(max) NULL
	,[direct_vacant_space] int NULL
	,[drive_ins] nvarchar(max) NULL
	,[energy_star] nvarchar(max) NULL
	,[exp_year] nvarchar(max) NULL
	,[features] nvarchar(max) NULL
	,[for_sale_price] nvarchar(max) NULL
	,[for_sale_status] nvarchar(1) NULL
	,[gas] nvarchar(max) NULL
	,[heating] nvarchar(max) NULL
	,[leed_certified] nvarchar(max) NULL
	,[land_area_(ac)] numeric(38,8) NULL
	,[last_sale_date] smalldatetime NULL
	,[last_sale_price] numeric(38,8) NULL
	,[latitude] numeric(38,8) NULL
	,[leasing_company_address] nvarchar(max) NULL
	,[leasing_company_city_state_zip] nvarchar(max) NULL
	,[leasing_company_contact] nvarchar(max) NULL
	,[leasing_company_fax] bigint NULL
	,[leasing_company_name] nvarchar(max) NULL
	,[leasing_company_phone] bigint NULL
	,[longitude] numeric(38,8) NULL
	,[market_name] nvarchar(max) NULL
	,[max_building_contiguous_space] numeric(38,8) NULL
	,[max_floor_contiguous_space] numeric(38,8) NULL
	,[number_of_1_bedrooms] smallint NULL
	,[number_of_2_bedrooms] smallint NULL
	,[number_of_3_bedrooms] smallint NULL
	,[number_of_cranes] smallint NULL
	,[number_of_elevators] smallint NULL
	,[number_of_loading_docks] smallint NULL
	,[number_of_parking_spaces] int NULL
	,[number_of_stories] smallint NULL
	,[number_of_studios] smallint NULL
	,[number_of_units] int NULL
	,[office_space] nvarchar(max) NULL
	,[ops_expense] numeric(38,8) NULL
	,[ops_expense_per_sf] numeric(38,8) NULL
	,[owner_address] nvarchar(max) NULL
	,[owner_city_state_zip] nvarchar(max) NULL
	,[owner_contact] nvarchar(max) NULL
	,[owner_name] nvarchar(max) NULL
	,[owner_phone] nvarchar(max) NULL
	,[parking_ratio] numeric(38,8) NULL
	,[percent_leased] numeric(38,8) NULL
	,[power] nvarchar(max) NULL
	,[primary_agent_name] nvarchar(max) NULL
	,[property_manager_address] nvarchar(max) NULL
	,[property_manager_city_state_zip] nvarchar(max) NULL
	,[property_manager_contact] nvarchar(max) NULL
	,[property_manager_name] nvarchar(max) NULL
	,[property_manager_phone] nvarchar(max) NULL
	,[propertytype] nvarchar(max) NULL
	,[rail_lines] nvarchar(max) NULL
	,[rentable_building_area] int NULL
	,[serial] nvarchar(max) NULL
	,[services] nvarchar(max) NULL
	,[sewer] nvarchar(max) NULL
	,[smallest_available_space] numeric(38,8) NULL
	,[sprinklers] nvarchar(max) NULL
	,[state] nvarchar(2) NULL
	,[sublet_available_space] numeric(38,8) NULL
	,[sublet_services] nvarchar(max) NULL
	,[sublet_vacant_space] nvarchar(max) NULL
	,[submarket_cluster] nvarchar(max) NULL
	,[submarket_name] nvarchar(max) NULL
	,[tax_year] int NULL
	,[taxes_per_sf] numeric(38,8) NULL
	,[taxes_total] numeric(38,8) NULL
	,[total_available_space_(sf)] int NULL
	,[total_new_space_(sf)] int NULL
	,[total_relet_space_(sf)] int NULL
	,[total_sublet_space_(sf)] int NULL
	,[total_vacant_avail_relet_space_(sf)] int NULL
	,[total_vacant_avail_sublet_space_(sf)] int NULL
	,[total_vacant_available] int NULL
	,[typical_floor_size] int NULL
	,[water] nvarchar(max) NULL
	,[year_built] int NULL
	,[year_renovated] int NULL
	,[zip] int NULL
	,[zoning] nvarchar(max) NULL
	,[$price/unit] numeric(38,8) NULL
	,[%_1_bed] numeric(38,8) NULL
	,[%_2_bed] numeric(38,8) NULL
	,[%_3_bed] numeric(38,8) NULL
	,[%_4_bed] numeric(38,8) NULL
	,[%_studios] numeric(38,8) NULL
	,[affordable_type] nvarchar(max) NULL
	,[anchor_gla] nvarchar(max) NULL
	,[avg_asking/sf] numeric(38,8) NULL
	,[avg_asking/unit] numeric(38,8) NULL
	,[avg_concessions_%] numeric(38,8) NULL
	,[avg_effective/sf] numeric(38,8) NULL
	,[avg_effective/unit] numeric(38,8) NULL
	,[avg_unit_sf] numeric(38,8) NULL
	,[cap_rate] numeric(38,8) NULL
	,[days_on_market] int NULL
	,[four_bedroom_asking_rent/sf] numeric(38,8) NULL
	,[four_bedroom_asking_rent/unit] numeric(38,8) NULL
	,[four_bedroom_avg_sf] numeric(38,8) NULL
	,[four_bedroom_concessions_%] numeric(38,8) NULL
	,[four_bedroom_effective_rent/sf] numeric(38,8) NULL
	,[four_bedroom_effective_rent/unit] numeric(38,8) NULL
	,[four_bedroom_vacancy_%] numeric(38,8) NULL
	,[four_bedroom_vacant_units] int NULL
	,[market_segment] nvarchar(max) NULL
	,[number_of_4_bedrooms] int NULL
	,[one_bedroom_asking_rent/sf] numeric(38,8) NULL
	,[one_bedroom_asking_rent/unit] numeric(38,8) NULL
	,[one_bedroom_avg_sf] numeric(38,8) NULL
	,[one_bedroom_concessions_%] numeric(38,8) NULL
	,[one_bedroom_effective_rent/sf] numeric(38,8) NULL
	,[one_bedroom_effective_rent/unit] numeric(38,8) NULL
	,[one_bedroom_vacancy_%] numeric(38,8) NULL
	,[one_bedroom_vacant_units] int NULL
	,[parcel_number_1(min)] nvarchar(max) NULL
	,[parcel_number_2(max)] nvarchar(max) NULL
	,[parking_spaces/unit] int NULL
	,[rent_type] nvarchar(max) NULL
	,[secondary_type] nvarchar(max) NULL
	,[star_rating] nvarchar(max) NULL
	,[studio_asking_rent/sf] numeric(38,8) NULL
	,[studio_asking_rent/unit] numeric(38,8) NULL
	,[studio_avg_sf] numeric(38,8) NULL
	,[studio_concessions_%] numeric(38,8) NULL
	,[studio_effective_rent/sf] numeric(38,8) NULL
	,[studio_effective_rent/unit] numeric(38,8) NULL
	,[studio_vacancy_%] numeric(38,8) NULL
	,[studio_vacant_units] int NULL
	,[style] nvarchar(max) NULL
	,[three_bedroom_asking_rent/sf] numeric(38,8) NULL
	,[three_bedroom_asking_rent/unit] numeric(38,8) NULL
	,[three_bedroom_avg_sf] numeric(38,8) NULL
	,[three_bedroom_concessions_%] numeric(38,8) NULL
	,[three_bedroom_effective_rent/sf] numeric(38,8) NULL
	,[three_bedroom_effective_rent/unit] numeric(38,8) NULL
	,[three_bedroom_vacancy_%] numeric(38,8) NULL
	,[three_bedroom_vacant_units] int NULL
	,[total_buildings] int NULL
	,[two_bedroom_asking_rent/sf] numeric(38,8) NULL
	,[two_bedroom_asking_rent/unit] numeric(38,8) NULL
	,[two_bedroom_avg_sf] numeric(38,8) NULL
	,[two_bedroom_concessions_%] numeric(38,8) NULL
	,[two_bedroom_effective_rent/sf] numeric(38,8) NULL
	,[two_bedroom_effective_rent/unit] numeric(38,8) NULL
	,[two_bedroom_vacancy_%] numeric(38,8) NULL
	,[two_bedroom_vacant_units] int NULL
	,[vacancy_%] numeric(38,8) NULL
	,[centroid] geometry NULL
	CONSTRAINT pk_input_costar_property_id PRIMARY KEY (property_id)
)
GO
