name: hlcm

model_type: segmented_locationchoice

segmentation_col: segmentation_col

choosers_fit_filters:
- building_id > 0

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 50

estimation_sample_size: 15000

default_config:
    model_expression: sqft_per_unit + year_built + residential_units

models:
    &id001 !!python/long '1':
        fit_parameters:
            Coefficient:
                residential_units: 0.03796867722438656
                sqft_per_unit: -5.022964916183432e-07
                year_built: 0.0028107139366836034
            Std. Error:
                residential_units: 0.00015120135752170907
                sqft_per_unit: 3.200866100040393e-07
                year_built: 4.781932863696629e-06
            T-Score:
                residential_units: 251.11333553295063
                sqft_per_unit: -1.5692518084777258
                year_built: 587.7777912822488
        fitted: true
        log_likelihoods:
            convergence: -49427.63463086342
            'null': -58680.34508140402
            ratio: 0.15767989158388251
        name: *id001

fitted: true
