name: networks

desc: Neighborhood Accessibility Variables

model_type: networks

node_col: node_id

variable_definitions:

  - name: jobs
    dataframe: jobs
    radius: 3000
    apply: np.log1p
    
  - name: jobs1
    dataframe: jobs
    filters:
    - sector_id == 1
    radius: 1200
    apply: np.log1p
    
  - name: jobs2
    dataframe: jobs
    filters:
    - sector_id == 2
    radius: 1200
    apply: np.log1p

  - name: jobs3
    dataframe: jobs
    filters:
    - sector_id == 3
    radius: 1200
    apply: np.log1p
    
  - name: jobs4
    dataframe: jobs
    filters:
    - sector_id == 4
    radius: 1200
    apply: np.log1p
    
  - name: jobs5
    dataframe: jobs
    filters:
    - sector_id == 5
    radius: 1200
    apply: np.log1p
    
  - name: jobs6
    dataframe: jobs
    filters:
    - sector_id == 6
    radius: 1200
    apply: np.log1p
    
  - name: jobs7
    dataframe: jobs
    filters:
    - sector_id == 7
    radius: 1200
    apply: np.log1p
    
  - name: jobs8
    dataframe: jobs
    filters:
    - sector_id == 8
    radius: 1200
    apply: np.log1p
    
  - name: jobs9
    dataframe: jobs
    filters:
    - sector_id == 9
    radius: 1200
    apply: np.log1p
    
  - name: jobs10
    dataframe: jobs
    filters:
    - sector_id == 10
    radius: 1200
    apply: np.log1p
    
  - name: jobs11
    dataframe: jobs
    filters:
    - sector_id == 11
    radius: 1200
    apply: np.log1p
    
  - name: jobs12
    dataframe: jobs
    filters:
    - sector_id == 12
    radius: 1200
    apply: np.log1p
    
  - name: jobs13
    dataframe: jobs
    filters:
    - sector_id == 13
    radius: 1200
    apply: np.log1p
    
  - name: jobs14
    dataframe: jobs
    filters:
    - sector_id == 14
    radius: 1200
    apply: np.log1p
    
  - name: jobs15
    dataframe: jobs
    filters:
    - sector_id == 15
    radius: 1200
    apply: np.log1p
    
  - name: jobs16
    dataframe: jobs
    filters:
    - sector_id == 16
    radius: 1200
    apply: np.log1p
    
  - name: jobs17
    dataframe: jobs
    filters:
    - sector_id == 17
    radius: 1200
    apply: np.log1p
    
  - name: jobs18
    dataframe: jobs
    filters:
    - sector_id == 18
    radius: 1200
    apply: np.log1p
    
  - name: jobs19
    dataframe: jobs
    filters:
    - sector_id == 19
    radius: 1200
    apply: np.log1p
    
  - name: jobs20
    dataframe: jobs
    filters:
    - sector_id == 20
    radius: 1200
    apply: np.log1p
    
  - name: ave_parcel_size
    dataframe: parcels
    varname: parcel_acr
    radius: 800
    aggregation: average
    decay: flat
    apply: np.log1p

  # - name: ave_income
    # dataframe: households
    # varname: income
    # radius: 1500
    # aggregation: average
    # decay: flat
    # apply: np.log1p
