store: urbansim.h5

build_networks:
  max_distance: 10000 #Distance is feet
  on_ramp_distance: 2640
  parks_distance: 2640
  schools_distance: 5280
  transit_distance: 2640

aggregation_tables:
  - nodes

rsh_yaml: rsh_w_luz_rco.yaml

households_transition:
  add_columns:
    - income_quartile
  total_column: hh #total_number_of_households

jobs_transition:
  add_columns:
    - sector_id
  total_column: number_of_jobs

#DEFAULT LAND COST PER SQ FOOT, Used in the feasibility model
default_land_cost: 12.21

feasibility:
  parcel_filter: newest_building < 2010
  residential_to_yearly: True
#  pass_through:
#    - oldest_building
#    - total_sqft
#    - max_far
#    - max_dua
#    - land_cost
#    - residential
#    - min_max_fars
#    - max_far_from_dua
#    - max_height
#    - max_far_from_heights
#    - building_purchase_price
#    - building_purchase_price_sqft
#  msa_id:
#    nonres_price_shifter:
#      0: 0.59
#      1: 0.74
#      2: 1.26
#      3: 1.66
#      4: 1.46
#      5: 1.66
#      6: 1
#    res_price_shifter:
#      0: 0.42
#      1: 0.54
#      2: 1.18
#      3: 1.66
#      4: 1.38
#      5: 1.66
#      6: 1
#  target_luz:
#    0: 69
#    1: 70
#    2: 72
#  luz_shifter:
#    0: 0.78

residential_developer:
  target_vacancy: .08
  min_unit_size: 1000
  bldg_sqft_per_job: 400

non_residential_developer:
  target_vacancy: .49
  bldg_sqft_per_job: 400


# this maps building type ids to general building types
# basically just reduces dimensionality
building_type_map:
  1: Other
  2: Industrial
  3: Industrial
  4: Office
  5: Retail
  6: Other
  7: Other
  8: Other
  9: Other
  10: Other
  11: Other
  12: Other
  13: Other
  14: Other
  15: Other
  16: Other
  17: Other
  18: Other
  19: Residential
  20: Residential
  21: Residential
  22: Other
  23: Other
  24: Other
  25: Other
  26: Other
  27: Other
  28: Other
  29: Other
  30: Other
  31: Other



## Custom setting for feasibility##
sqftproforma_config:
  parcel_sizes : [10000.0]
  fars: [.1, .25, .5, .75, 1.0, 1.5, 1.8, 2.0, 2.25, 2.5, 2.75, 3.0, 3.25, 3.5, 3.75, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 9.0, 11.0]
  uses: [ 'residential']
  residential_uses: [True]

  #add in the disctionary while running nrh
  forms:
    residential: {residential: 1.0}
   ## retail: 1.0
   ## industrial: 1.0
   ## office: 1.0
   ## residential: 1.0
   ## mixedresidential:
   ##   retail: .1
   ##   residential: .9
   ## mixedoffice:
   ##   office: 0.7
   ##   residential: 0.3

  profit_factor : 1.1
  building_efficiency : .7
  parcel_coverage : .8
  cap_rate : .05

  #add the rest of the cost when running nhr
  parking_rates: {'residential': 1.0}
    ##retail: 2.0
    ##industrial: .6
    ##office: 1.0

  sqft_per_rate: 1000.0

  #add the rest of the cost when running nhr
  costs: {'residential': [170.0, 190.0, 210.0, 240.0]}
    #retail: [160.0, 175.0, 200.0, 230.0]
    #industrial: [140.0, 175.0, 200.0, 230.0]
    #office: [160.0, 175.0, 200.0, 230.0]

  parking_configs: ['surface', 'deck', 'underground']
  heights_for_costs: [15, 55, 120, .inf]
  parking_sqft_d: {'surface': 300.0, 'deck': 250.0, 'underground': 250.0}
  parking_cost_d: {'surface': 30, 'deck': 90, 'underground': 110}
  height_per_story: 12.0
  max_retail_height: 2.0
  max_industrial_height: 2.0

#yaml values for hard code values in variables.py

parcel_avg_pr_mult: .81
res_sales_price_multiplier: 1.2